/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PetugasStatusRouteImport } from './routes/petugas.status'
import { Route as PetugasRequestRouteImport } from './routes/petugas.request'
import { Route as PetugasProfileRouteImport } from './routes/petugas.profile'
import { Route as PetugasJadwalHariIniRouteImport } from './routes/petugas.jadwal-hari-ini'
import { Route as PetugasDashboardRouteImport } from './routes/petugas.dashboard'
import { Route as AppStatusRouteImport } from './routes/app.status'
import { Route as AppScheduleRouteImport } from './routes/app.schedule'
import { Route as AppRequestRouteImport } from './routes/app.request'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AdminSchedulesRouteImport } from './routes/admin.schedules'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminPetugasRouteImport } from './routes/admin.petugas'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PetugasStatusRoute = PetugasStatusRouteImport.update({
  id: '/petugas/status',
  path: '/petugas/status',
  getParentRoute: () => rootRouteImport,
} as any)
const PetugasRequestRoute = PetugasRequestRouteImport.update({
  id: '/petugas/request',
  path: '/petugas/request',
  getParentRoute: () => rootRouteImport,
} as any)
const PetugasProfileRoute = PetugasProfileRouteImport.update({
  id: '/petugas/profile',
  path: '/petugas/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PetugasJadwalHariIniRoute = PetugasJadwalHariIniRouteImport.update({
  id: '/petugas/jadwal-hari-ini',
  path: '/petugas/jadwal-hari-ini',
  getParentRoute: () => rootRouteImport,
} as any)
const PetugasDashboardRoute = PetugasDashboardRouteImport.update({
  id: '/petugas/dashboard',
  path: '/petugas/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStatusRoute = AppStatusRouteImport.update({
  id: '/app/status',
  path: '/app/status',
  getParentRoute: () => rootRouteImport,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/app/schedule',
  path: '/app/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRequestRoute = AppRequestRouteImport.update({
  id: '/app/request',
  path: '/app/request',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/app/dashboard',
  path: '/app/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSchedulesRoute = AdminSchedulesRouteImport.update({
  id: '/admin/schedules',
  path: '/admin/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/admin/requests',
  path: '/admin/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPetugasRoute = AdminPetugasRouteImport.update({
  id: '/admin/petugas',
  path: '/admin/petugas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/petugas': typeof AdminPetugasRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/profile': typeof AppProfileRoute
  '/app/request': typeof AppRequestRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/status': typeof AppStatusRoute
  '/petugas/dashboard': typeof PetugasDashboardRoute
  '/petugas/jadwal-hari-ini': typeof PetugasJadwalHariIniRoute
  '/petugas/profile': typeof PetugasProfileRoute
  '/petugas/request': typeof PetugasRequestRoute
  '/petugas/status': typeof PetugasStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/petugas': typeof AdminPetugasRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/profile': typeof AppProfileRoute
  '/app/request': typeof AppRequestRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/status': typeof AppStatusRoute
  '/petugas/dashboard': typeof PetugasDashboardRoute
  '/petugas/jadwal-hari-ini': typeof PetugasJadwalHariIniRoute
  '/petugas/profile': typeof PetugasProfileRoute
  '/petugas/request': typeof PetugasRequestRoute
  '/petugas/status': typeof PetugasStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/petugas': typeof AdminPetugasRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/profile': typeof AppProfileRoute
  '/app/request': typeof AppRequestRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/status': typeof AppStatusRoute
  '/petugas/dashboard': typeof PetugasDashboardRoute
  '/petugas/jadwal-hari-ini': typeof PetugasJadwalHariIniRoute
  '/petugas/profile': typeof PetugasProfileRoute
  '/petugas/request': typeof PetugasRequestRoute
  '/petugas/status': typeof PetugasStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin/petugas'
    | '/admin/profile'
    | '/admin/requests'
    | '/admin/schedules'
    | '/app/dashboard'
    | '/app/profile'
    | '/app/request'
    | '/app/schedule'
    | '/app/status'
    | '/petugas/dashboard'
    | '/petugas/jadwal-hari-ini'
    | '/petugas/profile'
    | '/petugas/request'
    | '/petugas/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin/petugas'
    | '/admin/profile'
    | '/admin/requests'
    | '/admin/schedules'
    | '/app/dashboard'
    | '/app/profile'
    | '/app/request'
    | '/app/schedule'
    | '/app/status'
    | '/petugas/dashboard'
    | '/petugas/jadwal-hari-ini'
    | '/petugas/profile'
    | '/petugas/request'
    | '/petugas/status'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/admin/petugas'
    | '/admin/profile'
    | '/admin/requests'
    | '/admin/schedules'
    | '/app/dashboard'
    | '/app/profile'
    | '/app/request'
    | '/app/schedule'
    | '/app/status'
    | '/petugas/dashboard'
    | '/petugas/jadwal-hari-ini'
    | '/petugas/profile'
    | '/petugas/request'
    | '/petugas/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AdminPetugasRoute: typeof AdminPetugasRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminSchedulesRoute: typeof AdminSchedulesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRequestRoute: typeof AppRequestRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppStatusRoute: typeof AppStatusRoute
  PetugasDashboardRoute: typeof PetugasDashboardRoute
  PetugasJadwalHariIniRoute: typeof PetugasJadwalHariIniRoute
  PetugasProfileRoute: typeof PetugasProfileRoute
  PetugasRequestRoute: typeof PetugasRequestRoute
  PetugasStatusRoute: typeof PetugasStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/petugas/status': {
      id: '/petugas/status'
      path: '/petugas/status'
      fullPath: '/petugas/status'
      preLoaderRoute: typeof PetugasStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/petugas/request': {
      id: '/petugas/request'
      path: '/petugas/request'
      fullPath: '/petugas/request'
      preLoaderRoute: typeof PetugasRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/petugas/profile': {
      id: '/petugas/profile'
      path: '/petugas/profile'
      fullPath: '/petugas/profile'
      preLoaderRoute: typeof PetugasProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/petugas/jadwal-hari-ini': {
      id: '/petugas/jadwal-hari-ini'
      path: '/petugas/jadwal-hari-ini'
      fullPath: '/petugas/jadwal-hari-ini'
      preLoaderRoute: typeof PetugasJadwalHariIniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/petugas/dashboard': {
      id: '/petugas/dashboard'
      path: '/petugas/dashboard'
      fullPath: '/petugas/dashboard'
      preLoaderRoute: typeof PetugasDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/status': {
      id: '/app/status'
      path: '/app/status'
      fullPath: '/app/status'
      preLoaderRoute: typeof AppStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/schedule': {
      id: '/app/schedule'
      path: '/app/schedule'
      fullPath: '/app/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/request': {
      id: '/app/request'
      path: '/app/request'
      fullPath: '/app/request'
      preLoaderRoute: typeof AppRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/schedules': {
      id: '/admin/schedules'
      path: '/admin/schedules'
      fullPath: '/admin/schedules'
      preLoaderRoute: typeof AdminSchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/admin/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/petugas': {
      id: '/admin/petugas'
      path: '/admin/petugas'
      fullPath: '/admin/petugas'
      preLoaderRoute: typeof AdminPetugasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AdminPetugasRoute: AdminPetugasRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminSchedulesRoute: AdminSchedulesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppProfileRoute: AppProfileRoute,
  AppRequestRoute: AppRequestRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppStatusRoute: AppStatusRoute,
  PetugasDashboardRoute: PetugasDashboardRoute,
  PetugasJadwalHariIniRoute: PetugasJadwalHariIniRoute,
  PetugasProfileRoute: PetugasProfileRoute,
  PetugasRequestRoute: PetugasRequestRoute,
  PetugasStatusRoute: PetugasStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
